# Generated by Django 3.1.4 on 2020-12-27 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_institusi', models.CharField(max_length=255)),
                ('provinsi_institusi', models.CharField(max_length=255)),
                ('kabupaten_institusi', models.CharField(max_length=255)),
                ('kecamatan_institusi', models.CharField(max_length=255)),
                ('alamat_institusi', models.CharField(max_length=255)),
                ('email_institusi', models.CharField(blank=True, max_length=255)),
                ('kontak_institusi', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
