# Generated by Django 3.1.4 on 2021-01-10 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0002_auto_20210110_2119'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='kontak_sekolah',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
