# Generated by Django 3.1.4 on 2021-01-10 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0004_auto_20210110_2126'),
    ]

    operations = [
        migrations.RenameField(
            model_name='institution',
            old_name='alamat_institusi',
            new_name='alamat_sekolah',
        ),
        migrations.RenameField(
            model_name='institution',
            old_name='email_institusi',
            new_name='email_sekolah',
        ),
        migrations.RenameField(
            model_name='institution',
            old_name='kabupaten_institusi',
            new_name='kabupaten_sekolah',
        ),
        migrations.RenameField(
            model_name='institution',
            old_name='kecamatan_institusi',
            new_name='kecamatan_sekolah',
        ),
        migrations.RenameField(
            model_name='institution',
            old_name='kontak_institusi',
            new_name='kontak_sekolah',
        ),
        migrations.RenameField(
            model_name='institution',
            old_name='nama_institusi',
            new_name='nama_sekolah',
        ),
        migrations.RenameField(
            model_name='institution',
            old_name='provinsi_institusi',
            new_name='provinsi_sekolah',
        ),
    ]
