# Generated by Django 3.1.5 on 2021-02-04 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semifinals', '0004_jawabansemifinalsd_result_peserta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jawabansemifinalsd',
            name='result_peserta',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
