# Generated by Django 3.1.5 on 2021-02-06 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semifinals', '0005_auto_20210204_1644'),
    ]

    operations = [
        migrations.CreateModel(
            name='JawabanSemifinalSMA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_peserta', models.CharField(max_length=255)),
                ('nama_peserta', models.CharField(max_length=255)),
                ('exam_code', models.CharField(max_length=255)),
                ('paket_soal', models.CharField(max_length=10)),
                ('jawaban_peserta', models.CharField(max_length=255)),
                ('result_peserta', models.PositiveIntegerField(blank=True, null=True)),
                ('jawaban_benar', models.PositiveIntegerField(blank=True, null=True)),
                ('jawaban_salah', models.PositiveIntegerField(blank=True, null=True)),
                ('jawaban_kosong', models.PositiveIntegerField(blank=True, null=True)),
                ('submit_time', models.TimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='JawabanSemifinalSMP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_peserta', models.CharField(max_length=255)),
                ('nama_peserta', models.CharField(max_length=255)),
                ('exam_code', models.CharField(max_length=255)),
                ('paket_soal', models.CharField(max_length=10)),
                ('jawaban_peserta', models.CharField(max_length=255)),
                ('result_peserta', models.PositiveIntegerField(blank=True, null=True)),
                ('jawaban_benar', models.PositiveIntegerField(blank=True, null=True)),
                ('jawaban_salah', models.PositiveIntegerField(blank=True, null=True)),
                ('jawaban_kosong', models.PositiveIntegerField(blank=True, null=True)),
                ('submit_time', models.TimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SoalSemifinalSMA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_soal', models.PositiveIntegerField()),
                ('foto_soal', models.ImageField(upload_to='img/img_soal')),
                ('paket_soal', models.CharField(choices=[('A', 'Paket A'), ('B', 'Paket B'), ('C', 'Paket C'), ('D', 'Paket D'), ('E', 'Paket E')], max_length=10)),
                ('jawaban_soal', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='SoalSemifinalSMP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_soal', models.PositiveIntegerField()),
                ('foto_soal', models.ImageField(upload_to='img/img_soal')),
                ('paket_soal', models.CharField(choices=[('A', 'Paket A'), ('B', 'Paket B'), ('C', 'Paket C'), ('D', 'Paket D'), ('E', 'Paket E')], max_length=10)),
                ('jawaban_soal', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='jawabansemifinalsd',
            name='jawaban_benar',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jawabansemifinalsd',
            name='jawaban_kosong',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jawabansemifinalsd',
            name='jawaban_salah',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='soalsemifinalsd',
            name='no_soal',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
