# Generated by Django 3.1.5 on 2021-03-18 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semifinals', '0007_event_is_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jawabansemifinalsd',
            name='result_peserta',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
