# Generated by Django 3.1.5 on 2021-03-18 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semifinals', '0008_auto_20210319_0228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jawabansemifinalsma',
            name='result_peserta',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jawabansemifinalsmp',
            name='result_peserta',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
