# Generated by Django 3.1.5 on 2021-03-25 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semifinals', '0009_auto_20210319_0230'),
    ]

    operations = [
        migrations.AddField(
            model_name='jawabansemifinalsd',
            name='institusi_peserta',
            field=models.CharField(default='default', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jawabansemifinalsma',
            name='institusi_peserta',
            field=models.CharField(default='default', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jawabansemifinalsmp',
            name='institusi_peserta',
            field=models.CharField(default='default', max_length=255),
            preserve_default=False,
        ),
    ]
