# Generated by Django 3.1.5 on 2021-02-03 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balloons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='balloonsoalmodel',
            name='jawaban',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
