# Generated by Django 3.1.5 on 2021-03-11 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('balloons', '0004_event_is_start'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='is_start',
        ),
    ]
