# Generated by Django 3.1.5 on 2021-03-11 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balloons', '0005_remove_event_is_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_start',
            field=models.BooleanField(default=False),
        ),
    ]
