# Generated by Django 3.1.5 on 2021-02-18 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlayOffPenyisihanSD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_peserta', models.CharField(max_length=50)),
                ('nama_peserrta', models.CharField(max_length=255)),
                ('jawaban', models.CharField(max_length=255)),
                ('submit_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
