# Generated by Django 3.1.5 on 2021-01-14 15:08

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.user')),
                ('no_id', models.CharField(blank=True, max_length=255)),
                ('nisn_peserta', models.CharField(max_length=255)),
                ('jenis_kelamin', models.CharField(choices=[('Laki-laki', 'Laki-Laki'), ('Perempuan', 'Perempuan')], max_length=30)),
                ('tingkat', models.CharField(choices=[('SD', 'Sekolah Dasar'), ('SMP', 'Sekolah Menengah Pertama'), ('SMA', 'Sekolah Menengah Atas')], max_length=10)),
                ('kontak_peserta', models.CharField(blank=True, max_length=255)),
                ('email_peserta', models.EmailField(max_length=254)),
                ('foto_peserta', models.ImageField(upload_to='static/assets/img/img_peserta')),
                ('foto_rapor', models.ImageField(upload_to='static/assets/img/img_kartu_pelajar')),
                ('exam_code', models.CharField(blank=True, max_length=255)),
                ('penyisihan', models.BooleanField(default=False)),
                ('semifinal', models.BooleanField(default=False)),
                ('fastgame', models.BooleanField(default=False)),
                ('balloongame', models.BooleanField(default=False)),
                ('theatregame', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
