# Generated by Django 3.1.5 on 2021-01-14 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0003_auto_20210114_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='foto_peserta',
            field=models.ImageField(upload_to='static/assets/img/img_peserta'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='foto_rapor',
            field=models.ImageField(upload_to='static/assets/img/img_rapor'),
        ),
    ]
