# Generated by Django 3.1.5 on 2021-01-14 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0004_auto_20210114_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='foto_peserta',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='participant',
            name='foto_rapor',
            field=models.ImageField(upload_to=''),
        ),
    ]
