# Generated by Django 3.1.5 on 2021-01-18 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0005_auto_20210114_1917'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='paket_soal',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='participant',
            name='foto_peserta',
            field=models.ImageField(upload_to='media/img/img_peserta'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='foto_rapor',
            field=models.ImageField(upload_to='media/img/img_rapor'),
        ),
    ]
