# Generated by Django 3.1.5 on 2021-01-19 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0006_auto_20210118_2350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='foto_peserta',
            field=models.ImageField(upload_to='img/img_peserta'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='foto_rapor',
            field=models.ImageField(upload_to='img/img_rapor'),
        ),
    ]
