# Generated by Django 3.1.5 on 2021-02-19 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0008_auto_20210122_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='playoff_penyisihan',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='participant',
            name='playoff_semifinal',
            field=models.BooleanField(default=False),
        ),
    ]
