# Generated by Django 3.1.5 on 2021-03-09 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0009_auto_20210219_2357'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='is_login',
            field=models.BooleanField(default=False),
        ),
    ]
