# Generated by Django 3.1.5 on 2021-03-25 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0010_participant_is_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='playoff_balloon',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='participant',
            name='playoff_fast',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='participant',
            name='playoff_theatre',
            field=models.BooleanField(default=False),
        ),
    ]
