# Generated by Django 3.1.5 on 2021-03-11 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fasts', '0003_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_start',
            field=models.BooleanField(default=False),
        ),
    ]
