# Generated by Django 3.1.5 on 2021-03-16 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fasts', '0004_event_is_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='jawabanfastmodel',
            name='jawaban_benar',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jawabanfastmodel',
            name='jawaban_kosong',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jawabanfastmodel',
            name='jawaban_salah',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jawabanfastmodel',
            name='paket_soal',
            field=models.CharField(default='A', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jawabanfastmodel',
            name='result_peserta',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
