# Generated by Django 3.1.5 on 2021-03-18 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fasts', '0006_auto_20210317_0056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jawabanfastmodel',
            name='result_peserta',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
