# Generated by Django 3.1.5 on 2021-01-19 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('penyisihans', '0002_remove_soalpenyisihansd_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soalpenyisihansd',
            name='foto_soal',
            field=models.ImageField(upload_to='img/img_soal'),
        ),
    ]
