# Generated by Django 3.1.5 on 2021-01-19 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('penyisihans', '0003_auto_20210119_1632'),
    ]

    operations = [
        migrations.CreateModel(
            name='JawabanPenyisihanSD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_peserta', models.CharField(max_length=255)),
                ('nama_peserta', models.CharField(max_length=255)),
                ('exam_code', models.CharField(max_length=255)),
                ('paket_soal', models.CharField(max_length=10)),
                ('jawaban_peserta', models.CharField(max_length=255)),
                ('submit_time', models.TimeField(auto_now_add=True)),
            ],
        ),
    ]
