# Generated by Django 3.1.5 on 2021-01-20 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('penyisihans', '0004_jawabanpenyisihansd'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoalPenyisihanSMP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto_soal', models.ImageField(upload_to='img/img_soal')),
                ('paket_soal', models.CharField(choices=[('A', 'Paket A'), ('B', 'Paket B'), ('C', 'Paket C'), ('D', 'Paket D'), ('E', 'Paket E')], max_length=10)),
                ('jawaban_soal', models.CharField(max_length=10)),
            ],
        ),
    ]
