# Generated by Django 3.1.5 on 2021-02-03 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('penyisihans', '0007_jawabanpenyisihansd_result_peserta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jawabanpenyisihansd',
            name='result_peserta',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
