# Generated by Django 3.1.5 on 2021-02-04 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('penyisihans', '0008_auto_20210203_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jawabanpenyisihansd',
            name='result_peserta',
            field=models.PositiveIntegerField(blank=True),
        ),
    ]
