# Generated by Django 3.1.5 on 2021-02-04 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('penyisihans', '0009_auto_20210204_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jawabanpenyisihansd',
            name='result_peserta',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
