# Generated by Django 3.1.5 on 2021-02-04 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('penyisihans', '0010_auto_20210204_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jawabanpenyisihansd',
            name='result_peserta',
            field=models.PositiveIntegerField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
