# Generated by Django 3.1.5 on 2021-02-04 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('penyisihans', '0012_auto_20210204_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='jawabanpenyisihansd',
            name='jawaban_benar',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jawabanpenyisihansd',
            name='jawaban_kosong',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jawabanpenyisihansd',
            name='jawaban_salah',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
