# Generated by Django 3.1.5 on 2021-02-05 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('penyisihans', '0013_auto_20210204_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='soalpenyisihansd',
            name='no_soal',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
