# Generated by Django 3.1.5 on 2021-03-09 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('penyisihans', '0015_auto_20210206_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='jawabanpenyisihansd',
            name='is_login',
            field=models.BooleanField(default=False),
        ),
    ]
