# Generated by Django 3.1.5 on 2021-03-09 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('penyisihans', '0016_jawabanpenyisihansd_is_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jawabanpenyisihansd',
            name='is_login',
        ),
    ]
