# Generated by Django 3.1.5 on 2021-03-11 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('penyisihans', '0017_remove_jawabanpenyisihansd_is_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_start',
            field=models.BooleanField(default=False),
        ),
    ]
