# Generated by Django 3.1.5 on 2021-03-16 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('penyisihans', '0018_event_is_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='jawabanpenyisihansd',
            name='jawaban_poin',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
