# Generated by Django 3.1.5 on 2021-03-16 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('penyisihans', '0019_jawabanpenyisihansd_jawaban_poin'),
    ]

    operations = [
        migrations.AddField(
            model_name='jawabanpenyisihansma',
            name='jawaban_poin',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jawabanpenyisihansmp',
            name='jawaban_poin',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
