# Generated by Django 3.1.5 on 2021-03-16 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('penyisihans', '0020_auto_20210317_0010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jawabanpenyisihansd',
            name='jawaban_poin',
        ),
        migrations.RemoveField(
            model_name='jawabanpenyisihansma',
            name='jawaban_poin',
        ),
        migrations.RemoveField(
            model_name='jawabanpenyisihansmp',
            name='jawaban_poin',
        ),
    ]
