# Generated by Django 3.1.5 on 2021-03-18 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('penyisihans', '0021_auto_20210317_0012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jawabanpenyisihansd',
            name='result_peserta',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jawabanpenyisihansma',
            name='result_peserta',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jawabanpenyisihansmp',
            name='result_peserta',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
