# Generated by Django 3.1.5 on 2021-03-25 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('penyisihans', '0023_jawabanpenyisihansmp_institusi_peserta'),
    ]

    operations = [
        migrations.AddField(
            model_name='jawabanpenyisihansd',
            name='institusi_peserta',
            field=models.CharField(default='default', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jawabanpenyisihansma',
            name='institusi_peserta',
            field=models.CharField(default='default', max_length=255),
            preserve_default=False,
        ),
    ]
