# Generated by Django 3.1.4 on 2020-12-27 07:13

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('institutions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.user')),
                ('nis_peserta', models.CharField(max_length=255)),
                ('tingkat', models.CharField(choices=[('SD', 'Sekolah Dasar'), ('SMP', 'Sekolah Menengah Pertama'), ('SMA', 'Sekolah Menengah Atas')], max_length=10)),
                ('kontak_peserta', models.CharField(blank=True, max_length=255)),
                ('foto_peserta', models.ImageField(upload_to='static/assets/img/img_peserta')),
                ('foto_kartu_pelajar', models.ImageField(upload_to='static/assets/img/img_kartu_pelajar')),
                ('institusi_peserta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institutions.institution')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
