# Generated by Django 3.1.4 on 2020-12-29 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0004_auto_20201229_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='balloongame',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='participant',
            name='fastgame',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='participant',
            name='penyisihan',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='participant',
            name='semifinal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='participant',
            name='theatregame',
            field=models.BooleanField(default=False),
        ),
    ]
