# Generated by Django 3.1.4 on 2021-01-10 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0006_auto_20210110_2306'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='no_peserta',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
