# Generated by Django 3.1.4 on 2021-01-10 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0007_participant_no_peserta'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participant',
            old_name='no_peserta',
            new_name='no_id',
        ),
    ]
