# Generated by Django 3.1.5 on 2021-02-03 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JawabanTheaterModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_code', models.CharField(max_length=255)),
                ('nama_peserta', models.CharField(max_length=255)),
                ('jawaban0', models.CharField(max_length=255)),
                ('jawaban1', models.CharField(max_length=255)),
                ('jawaban2', models.CharField(max_length=255)),
                ('jawaban3', models.CharField(max_length=255)),
                ('jawaban4', models.CharField(max_length=255)),
                ('jawaban5', models.CharField(max_length=255)),
                ('jawaban6', models.CharField(max_length=255)),
                ('jawaban7', models.CharField(max_length=255)),
                ('jawaban8', models.CharField(max_length=255)),
                ('jawaban9', models.CharField(max_length=255)),
            ],
        ),
    ]
