# Generated by Django 3.1.5 on 2021-02-03 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theaters', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jawabantheatermodel',
            name='jawaban0',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='jawabantheatermodel',
            name='jawaban1',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='jawabantheatermodel',
            name='jawaban2',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='jawabantheatermodel',
            name='jawaban3',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='jawabantheatermodel',
            name='jawaban4',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='jawabantheatermodel',
            name='jawaban5',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='jawabantheatermodel',
            name='jawaban6',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='jawabantheatermodel',
            name='jawaban7',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='jawabantheatermodel',
            name='jawaban8',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='jawabantheatermodel',
            name='jawaban9',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
