# Generated by Django 3.1.5 on 2021-02-06 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theaters', '0002_auto_20210204_0239'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jawabantheatermodel',
            name='jawaban0',
        ),
        migrations.RemoveField(
            model_name='jawabantheatermodel',
            name='jawaban1',
        ),
        migrations.RemoveField(
            model_name='jawabantheatermodel',
            name='jawaban2',
        ),
        migrations.RemoveField(
            model_name='jawabantheatermodel',
            name='jawaban3',
        ),
        migrations.RemoveField(
            model_name='jawabantheatermodel',
            name='jawaban4',
        ),
        migrations.RemoveField(
            model_name='jawabantheatermodel',
            name='jawaban5',
        ),
        migrations.RemoveField(
            model_name='jawabantheatermodel',
            name='jawaban6',
        ),
        migrations.RemoveField(
            model_name='jawabantheatermodel',
            name='jawaban7',
        ),
        migrations.RemoveField(
            model_name='jawabantheatermodel',
            name='jawaban8',
        ),
        migrations.RemoveField(
            model_name='jawabantheatermodel',
            name='jawaban9',
        ),
        migrations.AddField(
            model_name='jawabantheatermodel',
            name='jawaban',
            field=models.CharField(default='default', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jawabantheatermodel',
            name='no_soal',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
