# Generated by Django 3.1.5 on 2021-03-02 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theaters', '0003_auto_20210207_0015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jawabantheatermodel',
            name='jawaban',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
