# Generated by Django 3.1.5 on 2021-03-15 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theaters', '0006_event_is_start'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jawabantheatermodel',
            name='no_soal',
        ),
    ]
