# Generated by Django 3.1.5 on 2021-03-16 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theaters', '0007_remove_jawabantheatermodel_no_soal'),
    ]

    operations = [
        migrations.CreateModel(
            name='JawabanTheaterModelSMA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_code', models.CharField(max_length=255)),
                ('nama_peserta', models.CharField(max_length=255)),
                ('jawaban', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='JawabanTheaterModelSMP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_code', models.CharField(max_length=255)),
                ('nama_peserta', models.CharField(max_length=255)),
                ('jawaban', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='JawabanTheaterModel',
        ),
    ]
