# Generated by Django 3.1.4 on 2020-12-27 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Soal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto_soal', models.ImageField(upload_to='static/assets/img/img_soal')),
                ('jawaban_A', models.CharField(max_length=100)),
                ('jawaban_B', models.CharField(max_length=100)),
                ('jawaban_C', models.CharField(max_length=100)),
                ('jawaban_D', models.CharField(max_length=100)),
                ('jawaban_E', models.CharField(max_length=100)),
                ('jawaban_benar', models.CharField(choices=[('A', models.CharField(max_length=100)), ('B', models.CharField(max_length=100)), ('C', models.CharField(max_length=100)), ('D', models.CharField(max_length=100)), ('E', models.CharField(max_length=100))], max_length=100)),
            ],
        ),
    ]
