# Generated by Django 3.1.4 on 2020-12-27 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='soal',
            name='kategori',
            field=models.CharField(choices=[('Penyisihan', 'Penyisihan'), ('Semifinal', 'Semifinal'), ('Fastgame', 'Fastgame'), ('Balloongame', 'Balloongame')], default='Penyisihan', max_length=50),
            preserve_default=False,
        ),
    ]
