# Generated by Django 3.1.4 on 2020-12-27 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_soal_kategori'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jawaban',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_soal', models.CharField(max_length=255)),
                ('id_participant', models.CharField(max_length=255)),
                ('exam_code_participant', models.CharField(max_length=255)),
                ('jawaban_peserta', models.CharField(blank=True, max_length=100)),
                ('jawaban_benar', models.CharField(max_length=100)),
            ],
        ),
    ]
