# Generated by Django 3.1.4 on 2020-12-28 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0005_jawaban_result'),
    ]

    operations = [
        migrations.CreateModel(
            name='JawabanSemiFinal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_peserta', models.CharField(max_length=255)),
                ('id_peserta', models.CharField(max_length=255)),
                ('jawaban_peserta', models.CharField(max_length=255)),
                ('result', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
