# Generated by Django 3.1.4 on 2020-12-28 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0006_jawabansemifinal'),
    ]

    operations = [
        migrations.AddField(
            model_name='jawabansemifinal',
            name='exam_code',
            field=models.CharField(default='default', max_length=255),
            preserve_default=False,
        ),
    ]
