# Generated by Django 3.1.4 on 2020-12-28 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0007_jawabansemifinal_exam_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='jawaban',
            name='exam_code',
            field=models.CharField(default='default', max_length=255),
            preserve_default=False,
        ),
    ]
