# Generated by Django 3.1.4 on 2020-12-28 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0009_balloonsoal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balloonsoal',
            name='jawaban_benar',
            field=models.TextField(blank=True),
        ),
    ]
