# Generated by Django 3.1.4 on 2020-12-28 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0010_auto_20201228_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balloonsoal',
            name='foto_soal',
            field=models.ImageField(blank=True, upload_to='static/assets/img/img_soal'),
        ),
    ]
