# Generated by Django 3.1.4 on 2020-12-28 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0011_auto_20201228_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='soal',
            name='tingkat',
            field=models.CharField(choices=[('SD', 'Sekolah Dasar'), ('SMP', 'Sekolah Menengah Pertama'), ('SMA', 'Sekolah Menengah Atas')], default='SD', max_length=10),
            preserve_default=False,
        ),
    ]
