# Generated by Django 3.1.4 on 2020-12-29 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0014_balloonsoal_is_taken'),
    ]

    operations = [
        migrations.CreateModel(
            name='JawabanBalloon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_peserta', models.CharField(max_length=255)),
                ('id_peserta', models.CharField(max_length=255)),
                ('exam_code', models.CharField(max_length=255)),
                ('soal_peserta', models.CharField(max_length=50)),
                ('jawaban_peserta', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='balloonsoal',
            name='exam_code',
            field=models.CharField(default='default', max_length=255),
            preserve_default=False,
        ),
    ]
