# Generated by Django 3.1.4 on 2021-01-02 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0015_auto_20201229_1459'),
    ]

    operations = [
        migrations.CreateModel(
            name='FastSoal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soal', models.ImageField(blank=True, upload_to='static/assets/img/img_soal')),
            ],
        ),
    ]
